# Generated by Django 5.2.9 on 2025-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Parent'),
        ),
    ]
