# Generated by Django 5.2.9 on 2025-12-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateoption',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='dateoption',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dateoption',
            name='start_time',
        ),
    ]
