# Generated by Django 5.2.9 on 2025-12-22 12:00

import django.db.models.deletion
from django.db import migrations, models


def delete_all_votes(apps, schema_editor):
    """Delete all existing votes before migration"""
    Vote = apps.get_model('voting', 'Vote')
    Vote.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('voting', '0002_alter_dateoption_options_remove_dateoption_end_time_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_all_votes, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='children.child'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('date_option', 'child')},
        ),
    ]
