# Generated by Django 5.2.9 on 2025-12-22 13:00

import django.db.models.deletion
from django.db import migrations, models


def delete_null_votes(apps, schema_editor):
    """Delete all votes with null child before making field required"""
    Vote = apps.get_model('voting', 'Vote')
    Vote.objects.filter(child__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('voting', '0003_alter_vote_unique_together_vote_child_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_null_votes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vote',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='children.child'),
        ),
    ]
