# Generated by Django 5.2.9 on 2025-12-22 14:21

import django.db.models.deletion
from django.db import migrations, models


def delete_all_votes(apps, schema_editor):
    """Delete all existing votes before migration"""
    Vote = apps.get_model('voting', 'Vote')
    Vote.objects.all().delete()


def create_time_slots_for_existing_dates(apps, schema_editor):
    """Create time slots for existing date options"""
    DateOption = apps.get_model('voting', 'DateOption')
    TimeSlot = apps.get_model('voting', 'TimeSlot')
    
    for date_option in DateOption.objects.all():
        TimeSlot.objects.get_or_create(date_option=date_option, period='morning')
        TimeSlot.objects.get_or_create(date_option=date_option, period='lunch')
        TimeSlot.objects.get_or_create(date_option=date_option, period='afternoon')


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('voting', '0004_auto_20251222_1300'),
    ]

    operations = [
        migrations.RunPython(delete_all_votes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('morning', 'Matin'), ('lunch', 'Déjeuner'), ('afternoon', 'Après-midi')], max_length=10, verbose_name='Période')),
                ('date_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='voting.dateoption', verbose_name='Option de date')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['date_option', 'period'],
            },
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('date_option', 'period'), name='voting_timeslot_date_option_period_unique'),
        ),
        migrations.RunPython(create_time_slots_for_existing_dates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.timeslot', verbose_name='Créneau horaire'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='date_option',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('time_slot', 'child')},
        ),
        migrations.AlterField(
            model_name='vote',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.timeslot', verbose_name='Créneau horaire'),
        ),
    ]
