# Generated by Django 5.2.9 on 2025-12-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    """Migrate is_active field to status field"""
    DateGroup = apps.get_model('voting', 'DateGroup')
    # Update all records where is_active=False to status='inactive'
    DateGroup.objects.filter(is_active=False).update(status='inactive')
    # Keep existing status for records where is_active=True (they should already have 'active' or 'closed')


def reverse_migrate_status_to_is_active(apps, schema_editor):
    """Reverse migration: set is_active based on status"""
    DateGroup = apps.get_model('voting', 'DateGroup')
    # Set is_active=True for 'active' and 'closed' status
    DateGroup.objects.filter(status__in=['active', 'closed']).update(is_active=True)
    # Set is_active=False for 'inactive' status
    DateGroup.objects.filter(status='inactive').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_merge_status_fields'),
        ('voting', '0006_add_status_to_dategroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dategroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Groupe de dates', 'verbose_name_plural': 'Groupes de dates'},
        ),
        migrations.AlterModelOptions(
            name='dateoption',
            options={'ordering': ['date'], 'verbose_name': 'Option de date', 'verbose_name_plural': 'Options de dates'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-voted_at'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='voting_timeslot_date_option_period_unique',
        ),
        # Data migration: convert is_active to status before removing the field
        migrations.RunPython(migrate_is_active_to_status, reverse_migrate_status_to_is_active),
        migrations.RemoveField(
            model_name='dategroup',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='dategroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='dategroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_date_groups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='dategroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dategroup',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('closed', 'Fermé'), ('inactive', 'Inactif')], default='active', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='dategroup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='dateoption',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dateoption',
            name='date_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_options', to='voting.dategroup', verbose_name='Groupe de dates'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='children.child', verbose_name='Enfant'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('maybe', 'Peut-être')], max_length=5, verbose_name='Choix'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du vote'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date_option', 'period')},
        ),
    ]
