# Generated by Django 5.2.9 on 2026-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_add_vote_closing_date_to_dategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dategroup',
            name='max_children_over_6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max enfants >= 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='max_children_under_6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max enfants < 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='max_total_children',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max total enfants'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='restrict_children_over_6',
            field=models.BooleanField(default=False, verbose_name='Limiter enfants >= 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='restrict_children_under_6',
            field=models.BooleanField(default=False, verbose_name='Limiter enfants < 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='restrict_total_children',
            field=models.BooleanField(default=False, verbose_name='Limiter total enfants'),
        ),
    ]
