# Generated by Django 5.2.9 on 2026-09-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_dategroup_max_children_over_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dategroup',
            name='max_days_over_6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max nombre de jours réservés par enfant >= 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='max_days_under_6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max nombre de jours réservés par enfant < 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='restrict_days_over_6',
            field=models.BooleanField(default=False, verbose_name='Limiter nombre de jours réservés par enfant >= 6 ans'),
        ),
        migrations.AddField(
            model_name='dategroup',
            name='restrict_days_under_6',
            field=models.BooleanField(default=False, verbose_name='Limiter nombre de jours réservés par enfant < 6 ans'),
        ),
    ]
